USB_VID = 0x2886
USB_PID = 0x8156

USB_PRODUCT = "Seeed Xiao ESP32-S3"
USB_MANUFACTURER = "Seeed Studio"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_SIZE = 8MB
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_ESP_USB_SERIAL_JTAG = 1
